-- MySQL Script generated by MySQL Workbench
-- Wed Sep  7 17:51:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coletaIGTI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL AUTO_INCREMENT,
  `animal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_animal_estimacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pessoa` (
  `cod_pessoa` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hobbie` (
  `cod_hobbie` INT NOT NULL,
  `hobbie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hobbie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `clima` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pesquisa` (
  `cod_pesquisa` INT NOT NULL AUTO_INCREMENT,
  `data_pesquisa` DATE NULL,
  `valor_venda` DECIMAL(10,2) NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_hobbie` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  PRIMARY KEY (`cod_pesquisa`),
  INDEX `fk_venda_veiculo_modelo_veiculo1_idx` (`cod_animal_estimacao` ASC),
  INDEX `fk_venda_veiculo_pessoa1_idx` (`cod_pessoa` ASC),
  INDEX `fk_pesquisa_hobbie1_idx` (`cod_hobbie` ASC),
  INDEX `fk_pesquisa_bebida1_idx` (`cod_bebida` ASC),
  INDEX `fk_pesquisa_clima1_idx` (`cod_clima` ASC),
  CONSTRAINT `fk_venda_veiculo_modelo_veiculo1`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_hobbie1`
    FOREIGN KEY (`cod_hobbie`)
    REFERENCES `hobbie` (`cod_hobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
